# Generated by Django 2.1.15 on 2024-04-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungdung_app', '0002_auto_20240403_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinfo',
            name='smoking',
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='blood_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='heart_disease',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
